
---
- name: Run Jenkins Container
  become: yes
  gather_facts: yes
  hosts: webservers
  remote_user: ubuntu
  tasks:
  - name: Ensure jenkins directory on Docker host
    file:
      state: directory
      owner: 1000
      group: 1000
      path: /share/jenkins
  - name: Pull the latest official Jenkins Docker image
    docker_image:
      name: "jenkins:latest"
  - name: Create a container from the jenkins docker image
    docker_container:
      name: "jenkins-server"
      image: "jenkins"
      ports:
          - "8080:8080"
          - "50000:50000"
      volumes:
          - "/share/jenkins:/var/jenkins_home"
      state: present
      recreate: no
  